project:
  type: website

website:
  title: "Lifelong-Learner.github.io"
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      - text: "New"
        file: new.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ismaai008l
      - icon: twitter
        href: https://twitter.com/ismailTG3
format:
  html:
    theme: cosmo
    css: styles.css



