project:
  type: website

website:
  title: "Ismail's Personal Blog"
  navbar:
    right:
      - text: "Blog"
        file: blog.qmd
      - about.qmd
      - icon: github
        href: https://github.com/ismaai008l
      - icon: twitter
        href: https://twitter.com/ismailTG3
format:
  html:
    theme: cosmo
    css: styles.css
    highlight-style: github
    code-line-numbers: true
    code-tools: true
    code-block-bg: true
    code-overflow: scroll

language-aliases:
  c++17: cpp
  c++: cpp
  cpp17: cpp


